version: "3.8"
services:
  security-tests:
    labels:
      author: "Rodrigo Alves"
      author_github: "https://github.com/ralves20"
    image: ralves20/sec-tests:1.0
    working_dir: /app/security-tests
    volumes:
      - ./:/app/security-tests
      - /tmp/reportstst:/opt/job-reports
    command:
      "ls"