version: "3.8"
services:
  security-tests:
    labels:
      author: "Rodrigo Alves"
      author_github: "https://github.com/ralves20"
    image: ralves20/sec-tests:1.0
    working_dir: /app/security-tests
    environment:
      - REPOSITORY_PATH=$REPOSITORY_PATH
    volumes:
      - ./:/app/security-tests
      - ./job-reports:/opt/job-reports
      - ${REPOSITORY_PATH:-/dev/null}:${REPOSITORY_PATH:-/tmp/app}
    command:
      "ls"